export interface AgriProduct {
  id: number
  slug: string
  name: string
  description: string
  src: string
  tags?: string[]
  scientificName?: string
  origin?: string
  type?: string
  moisture?: string
  packaging?: string
  targetMarkets?: { region: string; buyers: string[] }[]
  specs?: { label: string; value: string }[]
}

export const PRODUCTS: AgriProduct[] = [
  {
    id: 1,
    slug: 'soybeans',
    name: 'Soybeans',
    scientificName: 'Glycine max',
    description: 'Premium-grade soybeans sourced from certified farms across Nigeria. Rich in protein, suitable for oil processing, animal feed, and direct export.',
    src: '/assets/images/soybeans.jpg',
    tags: ['Export', 'Protein Crop', 'Oil Seed'],
    origin: 'Nigeria (Benue, Kaduna, Kogi)',
    type: 'Yellow soybeans, cleaned and dried',
    moisture: 'Max 13%',
    packaging: '50kg PP bags or bulk',
    specs: [
      { label: 'Protein Content', value: 'Min 36%' },
      { label: 'Oil Content', value: 'Min 18%' },
      { label: 'Foreign Matter', value: 'Max 1%' },
      { label: 'Admixture', value: 'Max 2%' },
    ],
    targetMarkets: [
      { region: 'Asia', buyers: ['Soybean oil processors in China, India', 'Animal feed manufacturers'] },
      { region: 'Europe', buyers: ['Protein meal producers in Netherlands, Germany', 'Organic food processors'] },
    ],
  },
  {
    id: 2,
    slug: 'cocoa-beans',
    name: 'Cocoa Beans',
    scientificName: 'Theobroma cacao',
    description: 'Sun-dried and fermented cocoa beans of the highest quality. Traceable from farm to export, meeting EU and US import standards.',
    src: '/assets/images/cocoawebp.webp',
    tags: ['Export', 'Cash Crop', 'West Africa'],
    origin: 'Nigeria (Ondo, Osun, Cross River, Ogun)',
    type: 'Fermented and sun-dried cocoa beans',
    moisture: 'Max 7.5%',
    packaging: '60–65kg jute bags',
    specs: [
      { label: 'Grade', value: 'Grade 1 & Grade 2' },
      { label: 'Fermentation', value: 'Min 75%' },
      { label: 'Defects', value: 'Max 5% (Grade 1)' },
      { label: 'Fat Content', value: 'Min 48%' },
    ],
    targetMarkets: [
      { region: 'Europe', buyers: ['Chocolate manufacturers in Netherlands, Belgium, Germany', 'Cocoa processors and grinders'] },
      { region: 'North America', buyers: ['Confectionery companies in USA', 'Specialty chocolate brands'] },
    ],
  },
  {
    id: 3,
    slug: 'maize',
    name: 'Maize (Corn)',
    scientificName: 'Zea mays',
    description: 'Dried yellow maize grains ideal for food processing, animal feed production, and starch extraction. Consistently graded and cleaned.',
    src: '/assets/images/Maize.jpg',
    tags: ['Food Crop', 'Feed Grain', 'Processing'],
    origin: 'Nigeria (Kaduna, Kano, Nasarawa, Benue)',
    type: 'Dried yellow maize grain',
    moisture: 'Max 13.5%',
    packaging: '50kg PP bags or bulk',
    specs: [
      { label: 'Foreign Matter', value: 'Max 1%' },
      { label: 'Broken Grains', value: 'Max 4%' },
      { label: 'Aflatoxin', value: 'Max 10 ppb' },
      { label: 'Weevil Damage', value: 'Nil' },
    ],
    targetMarkets: [
      { region: 'Domestic', buyers: ['Animal feed mills across Nigeria', 'Starch and glucose processors'] },
      { region: 'West Africa', buyers: ['Food manufacturers in Ghana, Senegal', 'Commodity traders'] },
    ],
  },
  {
    id: 4,
    slug: 'cassava',
    name: 'Cassava',
    scientificName: 'Manihot esculenta',
    description: 'Fresh and processed cassava including dried chips and pellets. Suitable for ethanol production, starch extraction, and export markets.',
    src: '/assets/images/cassava.jpg',
    tags: ['Starch', 'Processed', 'Export'],
    origin: 'Nigeria (Benue, Kogi, Oyo, Ogun)',
    type: 'Dried cassava chips, cassava flour, fresh tubers',
    moisture: 'Max 14% (chips)',
    packaging: '50kg PP bags',
    specs: [
      { label: 'Starch Content', value: 'Min 65%' },
      { label: 'HCN', value: 'Max 10 mg/kg' },
      { label: 'Fiber Content', value: 'Max 4%' },
      { label: 'Sand/Silt', value: 'Max 3%' },
    ],
    targetMarkets: [
      { region: 'Europe', buyers: ['Starch processors in Netherlands, UK', 'Ethanol and biofuel producers'] },
      { region: 'Asia', buyers: ['Tapioca starch manufacturers in China, Thailand'] },
    ],
  },
  {
    id: 5,
    slug: 'sesame-seeds',
    name: 'Sesame Seeds',
    scientificName: 'Sesamum indicum',
    description: 'High-purity sesame seeds (natural and hulled) sourced from Benue, Nassarawa, and Jigawa states. Meets Japanese, Chinese, and EU quality benchmarks.',
    src: '/assets/images/sesame.webp',
    tags: ['Export', 'Oil Seed', 'Premium'],
    origin: 'Nigeria (Benue, Nassarawa, Jigawa, Yobe)',
    type: 'Natural white sesame seeds, hulled sesame seeds',
    moisture: 'Max 6%',
    packaging: '25kg or 50kg PP bags',
    specs: [
      { label: 'Purity', value: 'Min 99.95%' },
      { label: 'Oil Content', value: 'Min 50%' },
      { label: 'FFA', value: 'Max 2%' },
      { label: 'Foreign Matter', value: 'Max 0.1%' },
    ],
    targetMarkets: [
      { region: 'Asia', buyers: ['Sesame oil processors in China, Japan, South Korea', 'Tahini manufacturers'] },
      { region: 'Europe', buyers: ['Health food brands in Germany, Netherlands, UK', 'Bakery ingredient suppliers'] },
    ],
  },
  {
    id: 6,
    slug: 'palm-oil',
    name: 'Palm Oil',
    scientificName: 'Elaeis guineensis',
    description: 'Fresh crude palm oil (CPO) and refined palm olein available in bulk. Produced under responsible farming practices with complete documentation.',
    src: '/assets/images/palm-oil-main.png',
    tags: ['Oil', 'Export', 'Bulk'],
    origin: 'Nigeria (Cross River, Akwa Ibom, Rivers, Delta)',
    type: 'Crude palm oil (CPO), refined palm olein',
    moisture: 'Max 0.25%',
    packaging: 'Flexi tanks, ISO tanks, drums',
    specs: [
      { label: 'FFA', value: 'Max 5% (CPO)' },
      { label: 'IV (Iodine Value)', value: '50–55' },
      { label: 'Colour (CPO)', value: 'Max 3.5 Red' },
      { label: 'Impurities', value: 'Max 0.05%' },
    ],
    targetMarkets: [
      { region: 'Asia', buyers: ['Food manufacturers in India, Malaysia', 'Biodiesel producers'] },
      { region: 'Europe', buyers: ['Oleochemical companies in Netherlands, Germany', 'Food processing industry'] },
    ],
  },
  {
    id: 7,
    slug: 'irish-potatoes',
    name: 'Irish Potatoes',
    scientificName: 'Solanum tuberosum',
    description: 'Fresh Irish potatoes sourced from Jos Plateau and Kaduna highlands. Available in retail and bulk quantities for domestic distribution.',
    src: '/assets/images/potatos.jpg',
    tags: ['Fresh Produce', 'Domestic', 'Highlands'],
    origin: 'Nigeria (Plateau, Kaduna)',
    type: 'Fresh table potatoes',
    moisture: 'N/A (fresh produce)',
    packaging: '25kg mesh/jute bags',
    specs: [
      { label: 'Size', value: '45mm – 80mm diameter' },
      { label: 'Defects', value: 'Max 5%' },
      { label: 'Green Tubers', value: 'Nil' },
      { label: 'Shelf Life', value: '3–4 weeks (cool storage)' },
    ],
    targetMarkets: [
      { region: 'Domestic', buyers: ['Supermarkets and retailers across Nigeria', 'Hotels, restaurants, catering (HoReCa)'] },
    ],
  },
  {
    id: 9,
    slug: 'charcoal',
    name: 'Charcoal',
    description: 'High-grade hardwood charcoal produced from sustainably sourced Nigerian timber. Available in lump and briquette form, suitable for industrial, restaurant, and export markets.',
    src: '/assets/images/charcoal.jpg',
    tags: ['Export', 'Energy', 'Industrial'],
    origin: 'Nigeria (Kwara, Niger, Oyo)',
    type: 'Hardwood lump charcoal',
    moisture: 'Max 5%',
    packaging: '10kg, 15kg, 25kg PP bags',
    specs: [
      { label: 'Fixed Carbon', value: 'Min 75%' },
      { label: 'Ash Content', value: 'Max 6%' },
      { label: 'Volatile Matter', value: 'Max 25%' },
      { label: 'Calorific Value', value: 'Min 7,000 kcal/kg' },
    ],
    targetMarkets: [
      { region: 'Europe', buyers: ['BBQ and grilling brands in UK, Germany, Poland', 'Restaurant and hospitality suppliers'] },
      { region: 'Middle East', buyers: ['Shisha charcoal importers in UAE, Saudi Arabia'] },
    ],
  },
  {
    id: 10,
    slug: 'charcoal-briquettes',
    name: 'Charcoal Briquettes',
    description: 'Compressed charcoal briquettes offering longer burn time and consistent heat output. Ideal for BBQ, hospitality, and packaged retail export.',
    src: '/assets/images/charcoal-2.jpg',
    tags: ['Export', 'Briquettes', 'BBQ'],
    origin: 'Nigeria',
    type: 'Compressed hardwood charcoal briquettes',
    moisture: 'Max 4%',
    packaging: '3kg, 5kg, 10kg retail bags; bulk 25kg sacks',
    specs: [
      { label: 'Fixed Carbon', value: 'Min 78%' },
      { label: 'Ash Content', value: 'Max 5%' },
      { label: 'Burn Time', value: 'Min 2.5 hours' },
      { label: 'Ignition Time', value: 'Approx 15 minutes' },
    ],
    targetMarkets: [
      { region: 'Europe', buyers: ['BBQ retail brands in UK, Netherlands, Germany', 'Outdoor and garden product distributors'] },
      { region: 'Middle East', buyers: ['Wholesale importers in UAE, Kuwait'] },
    ],
  },
  {
    id: 11,
    slug: 'ginger',
    name: 'Ginger',
    scientificName: 'Zingiber officinale',
    description: 'Dried split ginger and fresh ginger. High oleoresin content, strong aroma and flavor profile. Sourced from Kaduna, Nasarawa, and Gombe states.',
    src: '/assets/images/ginger.jpg',
    tags: ['Export', 'Spice', 'Premium'],
    origin: 'Nigeria (Kaduna, Nasarawa, Gombe)',
    type: 'Air-dried split ginger, sun-dried',
    moisture: 'Max 10%',
    packaging: '50kg PP bags',
    specs: [
      { label: 'Oleoresin Content', value: 'Min 3.5%' },
      { label: 'Volatile Oil', value: 'Min 1.5 ml/100g' },
      { label: 'Ash Content', value: 'Max 8%' },
      { label: 'Foreign Matter', value: 'Max 1%' },
    ],
    targetMarkets: [
      { region: 'Europe', buyers: ['Spice companies in Netherlands, UK, Germany', 'Food processing and flavoring industry', 'Pharmaceutical extractors', 'Beverage and soft drink manufacturers'] },
      { region: 'Asia', buyers: ['Spice processors in India, China', 'Traditional medicine manufacturers'] },
    ],
  },
  {
    id: 12,
    slug: 'palm-oil-gallon',
    name: 'Palm Oil (Gallon)',
    description: 'Refined and packaged palm oil in 5L, 10L, and 25L gallon containers. Ready for retail distribution, food service, and wholesale domestic supply.',
    src: '/assets/images/palm-oil-gallon.jpg',
    tags: ['Oil', 'Packaged', 'Retail'],
    origin: 'Nigeria',
    type: 'Refined palm oil, packaged',
    moisture: 'Max 0.1%',
    packaging: '5L, 10L, 25L gallon containers',
    specs: [
      { label: 'FFA', value: 'Max 0.1%' },
      { label: 'Colour', value: 'Max 1.5 Red (5.25″ cell)' },
      { label: 'Iodine Value', value: '50–55' },
      { label: 'Peroxide Value', value: 'Max 2 meq/kg' },
    ],
    targetMarkets: [
      { region: 'Domestic', buyers: ['Supermarkets and retail chains', 'Hotels, restaurants, catering', 'Wholesale distributors'] },
    ],
  },
  {
    id: 13,
    slug: 'haricot-beans',
    name: 'Haricot Beans',
    scientificName: 'Phaseolus vulgaris',
    description: 'Clean, dried haricot (white) beans sourced from smallholder farms across Nigeria. Ideal for canning, food processing, and direct export to European and Asian markets.',
    src: '/assets/images/Harich-potato.webp',
    tags: ['Export', 'Legume', 'Processing'],
    origin: 'Nigeria (Benue, Taraba, Plateau)',
    type: 'Dried white haricot beans',
    moisture: 'Max 14%',
    packaging: '50kg PP bags',
    specs: [
      { label: 'Purity', value: 'Min 98%' },
      { label: 'Foreign Matter', value: 'Max 0.5%' },
      { label: 'Broken/Damaged', value: 'Max 2%' },
      { label: 'Protein Content', value: 'Min 21%' },
    ],
    targetMarkets: [
      { region: 'Europe', buyers: ['Canning factories in UK, Italy, Spain', 'Supermarket private label suppliers'] },
      { region: 'Asia', buyers: ['Food manufacturers in Japan, South Korea'] },
    ],
  },
  {
    id: 14,
    slug: 'sweet-potatoes',
    name: 'Sweet Potatoes',
    scientificName: 'Ipomoea batatas',
    description: 'Fresh sweet potatoes available in orange and white flesh varieties. Sourced from Benue and Plateau states, supplied in bulk bags for domestic retail and processing.',
    src: '/assets/images/sweet-potato-2.jpg',
    tags: ['Fresh Produce', 'Domestic', 'Tuber'],
    origin: 'Nigeria (Benue, Plateau)',
    type: 'Fresh sweet potatoes, orange and white flesh',
    moisture: 'N/A (fresh produce)',
    packaging: '25kg–50kg mesh bags',
    specs: [
      { label: 'Dry Matter', value: 'Min 25%' },
      { label: 'Beta-carotene (orange)', value: 'Min 100 μg/g' },
      { label: 'Defects', value: 'Max 5%' },
      { label: 'Shelf Life', value: '2–3 weeks (ambient)' },
    ],
    targetMarkets: [
      { region: 'Domestic', buyers: ['Supermarkets and open markets', 'Food processors and puree manufacturers'] },
    ],
  },
  {
    id: 15,
    slug: 'edible-oil',
    name: 'Edible Oil',
    description: 'High-quality refined edible oil available for domestic food service, retail packaging, and bulk industrial supply.',
    src: '/assets/images/edible-oil.webp',
    tags: ['Oil', 'Food Grade', 'Retail'],
    origin: 'Nigeria',
    type: 'Refined vegetable oil blend',
    moisture: 'Max 0.1%',
    packaging: '1L, 5L bottles; 25L jerricans; flexi tanks',
    specs: [
      { label: 'FFA', value: 'Max 0.1%' },
      { label: 'Peroxide Value', value: 'Max 2 meq/kg' },
      { label: 'Smoke Point', value: 'Min 220°C' },
      { label: 'Trans Fat', value: 'Nil' },
    ],
    targetMarkets: [
      { region: 'Domestic', buyers: ['Retail chains and supermarkets', 'Food service and catering companies'] },
      { region: 'West Africa', buyers: ['Wholesale distributors in Ghana, Cameroon, Benin'] },
    ],
  },
  {
    id: 16,
    slug: 'soybean-oil',
    name: 'Soybean Oil',
    description: 'Pure refined soybean oil extracted from premium-grade soybeans. Suitable for cooking, food manufacturing, and industrial applications.',
    src: '/assets/images/soyoil.jpg',
    tags: ['Oil', 'Export', 'Food Grade'],
    origin: 'Nigeria',
    type: 'Refined and degummed soybean oil',
    moisture: 'Max 0.1%',
    packaging: '1L, 5L bottles; 20L jerricans; flexi tanks (bulk)',
    specs: [
      { label: 'FFA', value: 'Max 0.05%' },
      { label: 'Peroxide Value', value: 'Max 1 meq/kg' },
      { label: 'Iodine Value', value: '125–140' },
      { label: 'Colour (Lovibond)', value: 'Max 3.0 Red' },
    ],
    targetMarkets: [
      { region: 'Domestic', buyers: ['Food manufacturers and processors', 'Retail and wholesale distributors'] },
      { region: 'West Africa', buyers: ["Importers in Ghana, Côte d'Ivoire, Senegal"] },
    ],
  },
]
